services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=bbddtaller'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=nomelase'
      - 'MYSQL_USER=myuser'
    ports:
      - '53435:3306' #Cambio el puerto por defecto del lado de la máquina. No del lado de docker.
