# Utilizamos una imagen de Maven con JDK 8, que es suficiente tanto para compilar como para ejecutar la aplicación
FROM maven:3.6.3-jdk-8

# Copiamos los archivos del proyecto al directorio de trabajo del contenedor
COPY src /usr/src/myapp/src
COPY pom.xml /usr/src/myapp

# Establecemos el directorio de trabajo
WORKDIR /usr/src/myapp

# Compilamos el proyecto y empaquetamos la aplicación usando Maven
# Este paso genera el archivo JAR en el directorio target/
RUN mvn compile

# Expone el puerto en el que tu aplicación escucha
EXPOSE 1500

# Comando para ejecutar la aplicación.

CMD ["java", "es.ubu.lsi.server.ChatServerImpl"]

